# Generated by Django 3.2.6 on 2021-10-28 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id_contato', models.AutoField(primary_key=True, serialize=False)),
                ('nome_contato', models.CharField(max_length=255)),
                ('num_contato', models.CharField(max_length=14)),
                ('email_contato', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Preletor',
            fields=[
                ('id_preletor', models.AutoField(primary_key=True, serialize=False)),
                ('nome_preletor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nome_evento', models.CharField(max_length=55)),
                ('ingressantes', models.ManyToManyField(related_name='ingressantes', to='core.Contato')),
                ('preletor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preletor', to='core.preletor')),
            ],
        ),
    ]
